### ISSUE TITLE
I can't download the .blend file, since the page isn't available.

### ISSUE THREAD

**Issue by LaMarrash** [LluisV/Z-Anatomy#5]
So recently I started working on prosthetics and want to get well educated on the underlying tissues and bones. I wanted to donwload the blend file, but the page is unavailable. Can i get it elsewere?

Cheers for this proyect man, looks very well made and will probably help alot of people!

**Comment by LluisV** [comment]
Unfortunately we stopped developing the project, and therefore, we stopped maintaining the website.
I'll send you an alternative way to download the .blend later today.

**Comment by LluisV** [comment]
https://drive.google.com/drive/folders/18M7IuH2ai2fl21Ud0YH1mSlNEPPmcZzq?usp=sharing

**Comment by LluisV** [comment]
Please let me know if that works.

**Comment by LaMarrash** [comment]
Thanks so much man!

**Comment by waldenn** [comment]
> Unfortunately we stopped developing the project, and therefore, we stopped maintaining the website. I'll send you an alternative way to download the .blend later today.

Hey LluisV, did you stop the project because of a lack of funding or something else? I think this project has a lot more potential. Maybe find more funding options? If you setup a "Github sponsor" link, I will chip in.

I was looking into your 3D model work this weekend, to use in my https://conze.pt project: https://twitter.com/conzept__/status/1733816639328563597

I would love to see a good and flexibel, web-based human anatomy browser, especially with Wikidata-entity relations!

Another question I had: Do you have some idea, how good the current 3D model data is (in terms of accuracy, scope and segmentation) compared to the commercial variants (like eg. Zygote Body 3D)? Is it good enough for medical school use?

**Comment by LluisV** [comment]
Hi @waldenn.

1) 
The project was paused for various reasons.
Summarizing:
Indeed, the project never had financing of any kind. That forced me and Gauthier (he is the one who compiled and repaired the 3D models among many other things) to find a living in other jobs, even though Gauthier tried very hard to find external financing. Unfortunately the license (CC-BY-SA) seems to be an impediment in this regard.
There were also some internal conflicts between me and Gauthier that made it impossible for us to continue working as a team.
Despite all this, I do not consider that the project is abandoned, since as long as there are people who find it useful and use it for what it was designed for (having access to a free and open source anatomical atlas), the project will remain alive.
In my case I am now focused on other projects, but it is possible that I will release news about Z-Anatomy soon.

2) 
The main objective was always to have a web-viewer that merged the Z-Anatomy models with a TA2-type search engine and Wikidata information. That was all part of our plan, and there were even conversations about it. Unfortunately the project stopped before that. I do not rule out that path being taken up again in the future. Creating a web-viewer wouldn't take much time.

3)
Unfortunately I cannot answer this question, since I am not the developer of the models nor am I an anatomist. All I can tell you is that, as far as I know, the models still need quite a bit of specialized work to be considered finished. I would not risk stating that they can be used as a reliable anatomical reference.

**Comment by waldenn** [comment]
Thanks for your response!

Some quick notes:
- I think the CC-BY-SA is the right license for this project. Though the initial dev/funding may come slower, it will keep people honest and collaborating. Slow and steady wins the race.
- I'm located in the Netherlands and saw [this article](https://www.surf.nl/open-anatomisch-3d-model-in-het-onderwijs) about Surf.nl wanting to build on this project. I send an email to Paul Gobée today, to hear what work they've been doing. This could be another funding source I think.
- Wonderful to hear you don't consider this project abandoned!  It is indeed important to have this kind of tooling open for free and adaptable. Looking forward to some news from you maybe!
- About the web-project. I will see what I can do to create a working web-client base on [Online3DViewer](https://twitter.com/Online3DViewer). I already have a self-hosted version running to experiment with [here](https://conze.pt/app/3D/#model=https://conze.pt/app/explore2/assets/models/human_body/gltf/skeleton.gltf,https://conze.pt/app/explore2/assets/models/human_body/gltf/nervous_system.gltf).
I don't yet know how to open multiple glTF files in Online3DViewer in the same view (it seems this is not possible), as a intermediate step before the [Blender hierarchy export issue](https://github.com/KhronosGroup/glTF-Blender-IO/issues/1456) getting fixed. You see any other ways to get the whole body models working with the correct annotation hierarchies? What do you see as the best way to link the annotations to Wikidata? Currently that link is missing I think, though there are translations for the labels, etc.
- I would love to email/chat more about this potential web project, if you have some time in the coming months. If you are open to that, please send me an email. Perhaps we can cooperate with some other people / funders on this. I think there is quite a bit of demand/goodwill for a better solution, than the current commercial ones. I'm willing to help find ways to get some funding for this and help along with the software work. I'm no 3D modeller / anatomy expert though.

**Comment by LluisV** [comment]
Hi @waldenn.

- Yes, I know the project Paul Gobée is working on. Gauthier was in contact with him, but as far as I know the conversations did not come to fruition (I did not participate in these conversations).
- To preserve the hierarchy of the models, I imported them in .fbx format into Unity. Unity allows export to WebGL, so it should be relatively easy to get the project running on the web.
- Wikidata has a public API. The intention was to use it to get body part definitions at runtime based on the name of the selected object.
- Finding financing is not an easy task, since all bureaucratic processes must be done through an organization. It involves a whole series of processes that take time, and that is exactly what I lack right now.
- I will be happy to keep in touch with you. As soon as I have time to dedicate to this project I will let you know.

**Comment by waldenn** [comment]
> To preserve the hierarchy of the models, I imported them in .fbx format into Unity. Unity allows export to WebGL, so it should be relatively easy to get the project running on the web.

I'm sure that can work, but I think using something more web-native (and with active UI development) like [Online3DViewer](https://twitter.com/Online3DViewer), will be more useful and performant for users, especially in the longer term.

I currently don't have a good "tool path" to get the hierarchy into a glTF format. Will take another look when I get some time again. FBX seems to heavy for that I think (maybe I'm wrong about this).

For the Wikidata linking I would like to use the [P1323](https://www.wikidata.org/wiki/Property:P1323) property ("Terminologia Anatomica 98 ID") and then use the Wikidata label-translations for the user interface. I heard work is being done / was done of a newer version of  TA, but that new version was not openly licensed.

I've done something similar [here](https://conze.pt/explore/knee?l=en&d=wikipedia,wikidata&t=link&u=%2Fapp%2Fwikipedia%2F%3Ft%3Dknee%26l%3Den%26qid%3DQ37425&s=true#). Would love to see that same hierarchy browser also working on your 3D human anatomy. There are just so many possibilities once that TA98 hierarchy is available in glb / gltf. This is why your project is a key component.

Once the above works, a good app URL-parameter design would be great:
 - select a body part  and zoom into it (and later perhaps allow multiple body part selection) 
 - select a tree of body parts (located under the selected part).
 - toggle: highlight a body part / only show that body part
 - ...and more

Take your time, no hurries. Lets make something great from this project!
